!****************************************************************************
!*  SCALASCA    http://www.scalasca.org/                                   **
!****************************************************************************
!*  Copyright (c) 1998-2013                                                **
!*  Forschungszentrum Juelich GmbH, Juelich Supercomputing Centre          **
!*                                                                         **
!*  Copyright (c) 2003-2008                                                **
!*  University of Tennessee, Innovative Computing Laboratory               **
!*                                                                         **
!*  See the file COPYRIGHT in the package base directory for details       **
!***************************************************************************/

!*-----------------------------------------------------------------------------
!*
!*  EPILOG Library (Event Processing, Investigating, and Logging)
!*
!*  - Simple Vampirtrace Compiler Interface
!* 
!*-----------------------------------------------------------------------------

        EXTERNAL VTINIT
        EXTERNAL VTFINI
        EXTERNAL VTTRACEON
        EXTERNAL VTTRACEOFF
        EXTERNAL VTSYMDEF
        EXTERNAL VTBEGIN
        EXTERNAL VTEND


