"Usage: opari2-config [OPTION] ... <command>\n"
"\n"
"\n"
"with the following commands:\n"
"\n"
"   --nm                       Prints the nm command.\n"
"\n"
"   --region-initialization    Prints the script used to create the\n"
"                              pomp2_init_regions.c file.\n"
"\n"
"   --create-pomp2-regions     Prints the whole command necessary\n"
"            <object files>    for creating the initialization file.\n"
"\n"
"   --awk-cmd                  [Deprecated, use --region-initialization instead.]\n"
"                              Prints the awk command.\n"
"\n"
"   --awk-script               [Deprecated, use --region-initialization instead.]\n"
"                              Prints the awk script. \n"
"\n"
"   --egrep                    [Deprecated, use --region-initialization instead.]\n"
"                              Prints the egrep command.\n"
"                              \n"
"   --cflags                   Prints compiler options to include \n"
"                              installed headers.\n"
"\n"
"   --version                  Prints the opari2 version number.\n"
"\n"
"   --interface-version        Prints the pomp2 API version that \n"
"                              instrumented files conform too.\n"
"\n"
"   --opari2-revision          Prints the revision number of the \n"
"                              OPARI2 package.\n"
"\n"
"   --common-revision          Prints the revision number of the\n"
"                              common package.\n"
"\n"
"   --help                     Prints this help text.\n"
"\n"
"and the following options:\n"
"\n"
"   [--build-check]           Tells opari2-config to use build paths\n"
"                             instead of install paths. Used for build \n"
"                             testing.\n"
"\n"
"   [--config=<config file>]  Reads in a configuration from the given \n"
"                             file.\n"
"\n"
"Report bugs to <scorep-bugs@groups.tu-dresden.de>.\n"
